### ISSUE TITLE
NetCDF: Malformed or unexpected Constraint

### ISSUE THREAD

**Issue by baccandr** [hmedrano/erddap-python#2]
I am trying to download some chlorophyll data from Nesdis using this ERDDAP client but I get the following error:
`[Errno -75] NetCDF: Malformed or unexpected Constraint: b'https://coastwatch.pfeg.noaa.gov/erddap/griddap/nesdisVHNSQchlaMonthly?chlor_a[53:55][0:0][793:260][26:9573]`

The error comes from the URL generation, it's enough to add `.nc` after `nesdisVHNSQchlaMonthl` to create a valid query, which can be used to download the data directly. 
Am I doing something wrong or is this a bug of the ERDDAPclient? 

Thanks already

Here the code to reproduce the error:
```
remote = ERDDAP_Griddap('https://coastwatch.pfeg.noaa.gov/erddap','nesdisVHNSQchlaMonthly')
remote.clearQuery()
data = (remote.setResultVariables(['chlor_a'])
            .setSubset(time=slice(dt.datetime(2016,6,15), dt.datetime(2016,8,15)),
                       altitude=0,
                       latitude=slice(60, 80), 
                       longitude=slice(-179, +179))
            .getxArray())
```

**Comment by hmedrano** [comment]
Hello Andrea,
The opendap url indeed is malformed, exactly the part where its slicing the latitude. .. **[793:260]** ..   The opendap format expects positional indexes for the query, and the indexes should be incrementing.
I looked on the `nesdisVHNSQchlaMonthly` dataset, and i found that the latitude dimension values goes from 89.75625 to -89.75625  .  Then changing your latitude slice to 80, 60 works fine.

```python
remote = ERDDAP_Griddap('https://coastwatch.pfeg.noaa.gov/erddap','nesdisVHNSQchlaMonthly')
remote.clearQuery()
data = (remote.setResultVariables(['chlor_a'])
              .setSubset(time=slice(dt.datetime(2016,6,15), dt.datetime(2016,8,15)),
                         altitude=0,
                         latitude=slice(80, 60), 
                         longitude=slice(-179, +179))
              .getxArray())
```

Hope it helps!

**Comment by baccandr** [comment]
Thanks a lot for the answer, now it works perfectly!
