### ISSUE TITLE
Use ncDataset to write to a nc file

### ISSUE THREAD

**Issue by piratepheasant** [hmedrano/erddap-python#3]
I'm a very new user and have succeeded at creating a netCDF4 Dataset object.

from erddapClient import ERDDAP_Griddap
remote = ERDDAP_Griddap('https://www.ncei.noaa.gov/erddap','NCOM_amseas_latest2d')
nc = remote.ncDataset

Is there a way to turn this into a netCDF file without having to go through the process of making a new netCDF file, e.g., 

from netCDF4 import Dataset
ncfile = Dataset('new.nc',mode='w',format='NETCDF3_CLASSIC')

and then add all of the dimensions, variables, etc. from the netCDF4 Dataset object, nc, to the newly created file?

Thanks so much for your help.

**Comment by hmedrano** [comment]
Hello Sunny, yes, you can save your request in a netcdf file, you can actually do this from the actual erddap website interface.
But one thing to remember is that `NCOM_amseas_latest2d` is a pretty heavy dataset. (check the size of the dimensions and the number of variables) 

So I think it may be better to subset your request.

Examples:

Subset your request and get a `xarray.Dataset`.
```
from erddapClient import ERDDAP_Griddap
remote = ERDDAP_Griddap('https://www.ncei.noaa.gov/erddap','NCOM_amseas_latest2d')

subset = ( remote.setResultVariables(['surf_el', 'surf_temp_flux'])
                 .setSubset(time='2022-05-28',
                            latitude=slice(14,32),
                            longitude=slice(262,282))
                 .getxArray())
```


Request the actual netcdf file from erddap and save the results.
```
from erddapClient import ERDDAP_Griddap
remote = ERDDAP_Griddap('https://www.ncei.noaa.gov/erddap','NCOM_amseas_latest2d')

subsetncFile = ( remote.setResultVariables(['surf_el', 'surf_temp_flux'])
                       .setSubset(time='2022-05-28',
                                  latitude=slice(14,32),
                                  longitude=slice(262,282))
                       .getData(filetype='nc'))

fb = open('amseas2d_subset.nc','wb')
fb.write(subsetncFile)
fb.close()
```

Let me know if this helps.

**Comment by piratepheasant** [comment]
Thank you for the great recommendations with examples - I have successfully tested them.

The second should meet my exact need, and I appreciate you showing me both options.

Kind regards,
Sunni
